### ISSUE TITLE
There is an error 

### ISSUE THREAD

**Issue by Developer-N** [persian-calendar/DroidPersianCalendar#873]
https://github.com/persian-calendar/DroidPersianCalendar/blob/f852020ad108504ceff9708d8054ebbaac0f7aa3/PersianCalendar/src/main/kotlin/com/byagowi/persiancalendar/ui/calendar/CalendarFragment.kt#L290

    java.lang.IllegalArgumentException: SavedStateProvider with the given key is already registered
        at androidx.savedstate.SavedStateRegistry.registerSavedStateProvider(SavedStateRegistry.java:111)
        at com.byagowi.persiancalendar.ui.calendar.CalendarFragment.onViewCreated(CalendarFragment.kt:291)
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3019)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:551)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1831)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1764)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:488)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by ebraminio** [comment]
خیلی به موقع بود گزارش دادید، ممنون :)

**Comment by Developer-N** [comment]
خواهش می کنم موفق باشید، خیلی از کدهاتون استفاده کردم :)
